language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
  - nightly-2017-05-03
dist: trusty
group: edge
sudo: required
os:
  - linux
  - osx
env:
  global:
    - NIGHTLY_VERSION=nightly-2017-05-03
    - CLIPPY_VERSION=0.0.131
    - RUST_BACKTRACE=1
    - PROJECT_NAME=crgp
    - PROJECT_LIB_NAME=crgp_lib
    - PROJECT_INTEGRATION_TEST=algorithm_execution
    - RUST_TEST_THREADS=1
cache: cargo
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libiberty-dev
      - cmake
      - gcc
      - binutils-dev
      - zlib1g-dev
before_script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$NIGHTLY_VERSION" ]]; then
      cargo install clippy --vers $CLIPPY_VERSION --force;
    fi'
script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$NIGHTLY_VERSION" ]]; then
      cargo clippy -- -D warnings;
    fi'
  - cargo doc --no-deps
  - cargo check --all
  - cargo test --all
  - cargo test --all --release
after_success:
  - bash scripts/kcov.sh
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
    - rust: nightly-2017-05-03
