image: atlassianlabs/buildpack-deps-rust

pipelines:
  branches:
    master:
      - step:
          script:
            - echo "Updates to rustup"                ; rustup self update
            - echo "Update Rust toolchain"            ; rustup update
            - echo "Build project"                    ; cargo build --release
            - echo "Run unit tests"                   ; cargo test --lib --release -v --no-fail-fast -- --nocapture --test
            - echo "Run documentation tests"          ; cargo test --doc --release -v --no-fail-fast -- --nocapture --test
            - echo "Run integration tests"            ; cargo test --test ${CARGO_LIB_NAME} --release -v --no-fail-fast -- --nocapture --test
            - echo "Run benchmark tests"              ; cargo test --lib --release -v --no-fail-fast -- --nocapture --bench
            - echo "Upload coverage"                  ; if [ $? -eq 0 ]; then bash <(curl -s https://codecov.io/bash); fi
