[package]
name = "crgp"
version = "0.2.0"
authors = ["Bastian Meyer <bastian@bastianmeyer.eu>"]
description = "A graph-parallel approach to reconstructing the influences within Retweet cascades."
repository = "https://bitbucket.org/BMeu/crgp"
readme = "README.md"
license-file = "LICENSE.txt"
keywords = ["twitter", "cascade", "reconstruct", "graph", "influence"]
categories = ["algorithms", "science", "command-line-interface"]

[lib]
name = "crgplib"

[dependencies]
abomonation = "0.4"
clap = "~2.21.0"
fine_grained = "0.1"
gag = "0.1"
lazy_static = "0.2"
regex = "0.2"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
timely = "0.1.0"
timely_communication = "0.1.5"
