[package]
name = "ccgp"
version = "0.1.0"
authors = ["BMeu <bastian@bastianmeyer.eu>"]

[[bin]]
name = "ccgp_bin"

[dependencies]
abomonation = "0.4"
fnv = "1.0.5"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
stopwatch = "0.0.7"
timely = "0.1.0"
