[package]
name = "cascadereconstruction_graphparallel"
version = "0.1.0"
authors = ["BMeu <bastian@bastianmeyer.eu>"]

[[bin]]
name = "cascadereconstruction_graphparallel_bin"

[dependencies]
fnv = "1.0.5"
stopwatch = "0.0.7"
timely = "0.1.0"
